application: water-test
version: vizz
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "latest"
- name: PIL
  version: "latest"
- name: ssl
  version: "latest"
- name: pycrypto
  version: "latest" 
- name: numpy
  version: "latest"

handlers:
- url: /.*
  script: api.handlers